title: Lei Yao(姚磊)
position: PhD in Artificial Intelligence
affiliation: School of Artificial Intelligence,Jilin University
email: yaolei25@mails.jlu.edu.cn
email_link: mailto:yaolei25@mails.jlu.edu.cn
github_link: https://github.com/leiyao1299
weixin: ./assets/img/weixin.png
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description:  A PhD of Artificial Intelligence at the School of Artificial Intelligence,Jilin University (JLU)
remote_theme: yaoyao-liu/strata-academic
